services:
  addisco-ops:
    build: .
    container_name: addisco-ops
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./database.db:/app/database.db
      - ./docs:/app/docs
    restart: unless-stopped
