"""Données de démonstration pour le cockpit formateur — TASK-056.

Activées automatiquement quand la cohorte réelle compte < 2 apprenants inscrits.
Structure prévue pour branchement réel futur : même shape que _build_real_learner().
"""
from typing import Any

MOCK_LEARNERS: list[dict[str, Any]] = [
    {
        "username": "M. Martin",
        "user_id": "mock_martin",
        "score": 0.82,
        "attempts": 63,
        "days_active": 18,
        "mastered_sections": 5,
        "fragile_sections": 1,
        "dominant_error": "reponse_vague",
        "profile": "Procédural",
        "profile_icon": "⚙️",
        "status": "active",
        "trend": "up",
        "momentum": 0.12,
        "last_active": "Aujourd'hui",
    },
    {
        "username": "S. Dubois",
        "user_id": "mock_dubois",
        "score": 0.61,
        "attempts": 31,
        "days_active": 7,
        "mastered_sections": 2,
        "fragile_sections": 4,
        "dominant_error": "confusion_notion",
        "profile": "Analytique",
        "profile_icon": "🔬",
        "status": "warning",
        "trend": "down",
        "momentum": -0.08,
        "last_active": "Hier",
    },
    {
        "username": "L. Bernard",
        "user_id": "mock_bernard",
        "score": 0.74,
        "attempts": 45,
        "days_active": 14,
        "mastered_sections": 3,
        "fragile_sections": 2,
        "dominant_error": "oubli_etape",
        "profile": "Narratif",
        "profile_icon": "📖",
        "status": "active",
        "trend": "stable",
        "momentum": 0.01,
        "last_active": "Il y a 2 jours",
    },
    {
        "username": "A. Chen",
        "user_id": "mock_chen",
        "score": 0.45,
        "attempts": 18,
        "days_active": 4,
        "mastered_sections": 0,
        "fragile_sections": 6,
        "dominant_error": "hors_sujet",
        "profile": "Analogique",
        "profile_icon": "🔗",
        "status": "critical",
        "trend": "down",
        "momentum": -0.15,
        "last_active": "Il y a 4 jours",
    },
]

MOCK_ADAPTIVE_PROFILES: list[dict[str, Any]] = [
    {
        "name": "Apprentissage séquentiel",
        "icon": "📋",
        "badge_bg": "#eef2ff",
        "badge_text": "#4338ca",
        "description": "Meilleurs résultats sur questions procédurales et étapes logiques structurées.",
        "impact": "Adapter les exercices par séquences d'étapes claires.",
        "learners": ["M. Martin", "L. Bernard"],
    },
    {
        "name": "Surcharge cognitive probable",
        "icon": "⚠️",
        "badge_bg": "#fef2f2",
        "badge_text": "#b91c1c",
        "description": "Temps de réponse élevés associés à des erreurs sur questions complexes.",
        "impact": "Réduire la longueur des questions, proposer des micro-boucles.",
        "learners": ["A. Chen"],
    },
    {
        "name": "Forte mémoire contextuelle",
        "icon": "🧠",
        "badge_bg": "#f0fdf4",
        "badge_text": "#15803d",
        "description": "Excellent rappel des cas pratiques et des situations concrètes.",
        "impact": "Privilégier les questions à contexte réel (cas pratiques).",
        "learners": ["M. Martin"],
    },
    {
        "name": "Amélioration par répétition espacée",
        "icon": "📅",
        "badge_bg": "#fffbeb",
        "badge_text": "#b45309",
        "description": "Progression visible après chaque cycle de révision espacée.",
        "impact": "Maintenir le rythme de révision adaptatif automatique.",
        "learners": ["S. Dubois", "L. Bernard"],
    },
]

MOCK_ALERTS: list[dict[str, Any]] = [
    {
        "severity": "critical",
        "icon": "🚨",
        "color": "#dc2626",
        "bg": "#fef2f2",
        "border": "#fecaca",
        "learner": "A. Chen",
        "message": "Score sous 50 % depuis 5 sessions consécutives — 6 sections fragiles identifiées.",
        "recommendation": "Planifier une révision guidée sur les sections les plus fragiles.",
    },
    {
        "severity": "warning",
        "icon": "⚠️",
        "color": "#b45309",
        "bg": "#fffbeb",
        "border": "#fde68a",
        "learner": "S. Dubois",
        "message": "Stagnation détectée — aucune progression mesurable sur les 7 derniers jours.",
        "recommendation": "Varier les types de questions et injecter du rappel actif.",
    },
    {
        "severity": "info",
        "icon": "💡",
        "color": "#1d4ed8",
        "bg": "#eff6ff",
        "border": "#bfdbfe",
        "learner": "Cohorte",
        "message": "Taux d'erreur 'confusion de notion' en hausse sur les 3 derniers jours.",
        "recommendation": "Renforcer les exercices de distinction entre notions proches.",
    },
]

MOCK_RECOMMENDATIONS: list[dict[str, Any]] = [
    {
        "icon": "🔄",
        "title": "Renforcer le rappel actif",
        "priority": "high",
        "description": "2 apprenants bénéficieraient d'une fréquence de révision accrue sur les sections fragiles identifiées.",
        "target": "S. Dubois, A. Chen",
    },
    {
        "icon": "📏",
        "title": "Adapter la longueur des questions",
        "priority": "medium",
        "description": "Surcharge cognitive détectée — réduire les questions à plus de 3 conditions simultanées.",
        "target": "A. Chen",
    },
    {
        "icon": "🎯",
        "title": "Varier les formulations",
        "priority": "medium",
        "description": "Proposer des reformulations alternatives pour les notions à erreur récurrente.",
        "target": "Cohorte",
    },
    {
        "icon": "⚡",
        "title": "Micro-boucles d'apprentissage",
        "priority": "low",
        "description": "Sessions courtes de 5 min + révision immédiate pour consolider les notions critiques.",
        "target": "M. Martin",
    },
]
